
# PU1 词汇数据 - 从 PDF 提取整理
# 格式: { unit_key: { title, words: [{word, phonetic, definition}] } }

PU1_VOCAB = {
  "pu1u0": {
    "title": "Hello",
    "words": [
      {"word": "red", "phonetic": "/rɛd/", "definition": "the colour of blood or fire"},
      {"word": "blue", "phonetic": "/bluː/", "definition": "the colour of the sky on a clear day"},
      {"word": "yellow", "phonetic": "/ˈjɛləʊ/", "definition": "the colour of the sun or a lemon"},
      {"word": "green", "phonetic": "/ɡriːn/", "definition": "the colour of grass and leaves"},
      {"word": "orange", "phonetic": "/ˈɒrɪndʒ/", "definition": "a colour between red and yellow"},
      {"word": "purple", "phonetic": "/ˈpɜːpl/", "definition": "a colour between red and blue"},
      {"word": "pink", "phonetic": "/pɪŋk/", "definition": "a light red colour"},
      {"word": "grey", "phonetic": "/ɡreɪ/", "definition": "a colour between black and white"},
      {"word": "black", "phonetic": "/blæk/", "definition": "the darkest colour, like the night sky"},
      {"word": "white", "phonetic": "/waɪt/", "definition": "the lightest colour, like snow"},
    ]
  },
  "pu1u1": {
    "title": "Our new school",
    "words": [
      {"word": "bag", "phonetic": "/bæɡ/", "definition": "a container used to carry things"},
      {"word": "book", "phonetic": "/bʊk/", "definition": "a set of printed pages held together"},
      {"word": "chair", "phonetic": "/tʃɛː/", "definition": "a separate seat for one person"},
      {"word": "classroom", "phonetic": "/ˈklɑːsruːm/", "definition": "a room in a school where lessons take place"},
      {"word": "crayon", "phonetic": "/ˈkreɪɒn/", "definition": "a coloured wax stick used for drawing"},
      {"word": "desk", "phonetic": "/dɛsk/", "definition": "a table used for writing or studying"},
      {"word": "pen", "phonetic": "/pɛn/", "definition": "a tool used for writing with ink"},
      {"word": "pencil", "phonetic": "/ˈpɛnsɪl/", "definition": "a thin stick used for writing or drawing"},
      {"word": "teacher", "phonetic": "/ˈtiːtʃə/", "definition": "a person who teaches in a school"},
      {"word": "pencil case", "phonetic": "/ˈpɛnsɪl keɪs/", "definition": "a small bag for holding pens and pencils"},
      {"word": "eraser", "phonetic": "/ɪˈreɪzə/", "definition": "a piece of rubber used to remove pencil marks"},
      {"word": "ruler", "phonetic": "/ˈruːlə/", "definition": "a straight strip used for measuring or drawing lines"},
      {"word": "paper", "phonetic": "/ˈpeɪpə/", "definition": "thin flat material used for writing or drawing"},
      {"word": "playground", "phonetic": "/ˈpleɪɡraʊnd/", "definition": "an outdoor area where children play"},
      {"word": "cupboard", "phonetic": "/ˈkʌbəd/", "definition": "a piece of furniture with shelves for storing things"},
      {"word": "door", "phonetic": "/dɔː/", "definition": "a movable barrier used to open or close an entrance"},
      {"word": "board", "phonetic": "/bɔːd/", "definition": "a flat surface on a wall used for writing in class"},
      {"word": "bookcase", "phonetic": "/ˈbʊkkeɪs/", "definition": "a piece of furniture with shelves for books"},
      {"word": "wall", "phonetic": "/wɔːl/", "definition": "a vertical structure that forms the side of a room"},
      {"word": "window", "phonetic": "/ˈwɪndəʊ/", "definition": "an opening in a wall fitted with glass"},
    ]
  },
  "pu1u2": {
    "title": "All about us",
    "words": [
      {"word": "family", "phonetic": "/ˈfæmɪli/", "definition": "a group of people related to each other"},
      {"word": "father", "phonetic": "/ˈfɑːðə/", "definition": "a male parent"},
      {"word": "dad", "phonetic": "/dæd/", "definition": "an informal word for father"},
      {"word": "mother", "phonetic": "/ˈmʌðə/", "definition": "a female parent"},
      {"word": "mom", "phonetic": "/mɒm/", "definition": "an informal word for mother"},
      {"word": "brother", "phonetic": "/ˈbrʌðə/", "definition": "a boy or man who has the same parents as you"},
      {"word": "sister", "phonetic": "/ˈsɪstə/", "definition": "a girl or woman who has the same parents as you"},
      {"word": "grandfather", "phonetic": "/ˈɡrænfɑːðə/", "definition": "the father of your mother or father"},
      {"word": "grandpa", "phonetic": "/ˈɡrænpɑː/", "definition": "an informal word for grandfather"},
      {"word": "grandmother", "phonetic": "/ˈɡrænmʌðə/", "definition": "the mother of your mother or father"},
      {"word": "grandma", "phonetic": "/ˈɡrænmɑː/", "definition": "an informal word for grandmother"},
      {"word": "hand", "phonetic": "/hænd/", "definition": "the part of the body at the end of the arm"},
      {"word": "head", "phonetic": "/hɛd/", "definition": "the top part of the body containing the brain"},
      {"word": "nose", "phonetic": "/nəʊz/", "definition": "the part of the face used for smelling and breathing"},
      {"word": "leg", "phonetic": "/lɛɡ/", "definition": "one of the limbs used for walking"},
      {"word": "mouth", "phonetic": "/maʊθ/", "definition": "the opening in the face used for eating and speaking"},
      {"word": "arm", "phonetic": "/ɑːm/", "definition": "the limb between the shoulder and the hand"},
      {"word": "ear", "phonetic": "/ɪə/", "definition": "the organ used for hearing"},
      {"word": "eye", "phonetic": "/aɪ/", "definition": "the organ used for seeing"},
      {"word": "face", "phonetic": "/feɪs/", "definition": "the front part of the head"},
      {"word": "body", "phonetic": "/ˈbɒdi/", "definition": "the whole physical structure of a person"},
      {"word": "feet", "phonetic": "/fiːt/", "definition": "the plural of foot; the parts at the bottom of the legs"},
      {"word": "hair", "phonetic": "/hɛː/", "definition": "the thin strands that grow on the head"},
    ]
  },
  "pu1u3": {
    "title": "Fun on the farm",
    "words": [
      {"word": "sheep", "phonetic": "/ʃiːp/", "definition": "a farm animal kept for its wool and meat"},
      {"word": "goat", "phonetic": "/ɡəʊt/", "definition": "a farm animal with horns that gives milk"},
      {"word": "horse", "phonetic": "/hɔːs/", "definition": "a large animal used for riding"},
      {"word": "donkey", "phonetic": "/ˈdɒŋki/", "definition": "a grey or brown animal like a small horse"},
      {"word": "duck", "phonetic": "/dʌk/", "definition": "a bird that lives near water and can swim"},
      {"word": "cow", "phonetic": "/kaʊ/", "definition": "a large farm animal that gives milk"},
      {"word": "dog", "phonetic": "/dɒɡ/", "definition": "a common pet animal that barks"},
      {"word": "cat", "phonetic": "/kæt/", "definition": "a small furry pet animal that meows"},
      {"word": "chicken", "phonetic": "/ˈtʃɪkɪn/", "definition": "a common farm bird kept for eggs and meat"},
      {"word": "spider", "phonetic": "/ˈspaɪdə/", "definition": "a small creature with eight legs that spins webs"},
      {"word": "sad", "phonetic": "/sæd/", "definition": "feeling unhappy or sorrowful"},
      {"word": "ugly", "phonetic": "/ˈʌɡli/", "definition": "not attractive or pleasant to look at"},
      {"word": "funny", "phonetic": "/ˈfʌni/", "definition": "causing laughter; amusing"},
      {"word": "happy", "phonetic": "/ˈhæpi/", "definition": "feeling pleased or joyful"},
      {"word": "angry", "phonetic": "/ˈæŋɡri/", "definition": "feeling strong displeasure or annoyance"},
      {"word": "beautiful", "phonetic": "/ˈbjuːtɪfʊl/", "definition": "very attractive or pleasing to look at"},
    ]
  },
  "pu1u4": {
    "title": "Food with friends",
    "words": [
      {"word": "mango", "phonetic": "/ˈmæŋɡəʊ/", "definition": "a sweet tropical fruit with yellow flesh"},
      {"word": "chocolate", "phonetic": "/ˈtʃɒklɪt/", "definition": "a sweet brown food made from cocoa"},
      {"word": "burger", "phonetic": "/ˈbɜːɡə/", "definition": "a round flat piece of meat in a bread roll"},
      {"word": "cake", "phonetic": "/keɪk/", "definition": "a sweet baked food made with flour and sugar"},
      {"word": "banana", "phonetic": "/bəˈnɑːnə/", "definition": "a long curved yellow fruit"},
      {"word": "bread", "phonetic": "/brɛd/", "definition": "a baked food made from flour and water"},
      {"word": "salad", "phonetic": "/ˈsæləd/", "definition": "a mixture of raw vegetables eaten as food"},
      {"word": "water", "phonetic": "/ˈwɔːtə/", "definition": "a clear liquid that we drink"},
      {"word": "lemonade", "phonetic": "/ˌlɛməˈneɪd/", "definition": "a sweet drink made from lemon juice"},
      {"word": "meatballs", "phonetic": "/ˈmiːtbɔːlz/", "definition": "small round balls of minced meat"},
      {"word": "juice", "phonetic": "/dʒuːs/", "definition": "a drink made from squeezed fruit"},
      {"word": "meat", "phonetic": "/miːt/", "definition": "the flesh of an animal used as food"},
      {"word": "fruit", "phonetic": "/fruːt/", "definition": "the sweet part of a plant that contains seeds"},
      {"word": "grapes", "phonetic": "/ɡreɪps/", "definition": "small round fruits that grow in clusters"},
      {"word": "apple", "phonetic": "/ˈæpl/", "definition": "a round fruit with red or green skin"},
      {"word": "beans", "phonetic": "/biːnz/", "definition": "small seeds eaten as vegetables"},
      {"word": "sausage", "phonetic": "/ˈsɒsɪdʒ/", "definition": "a tube of minced meat in a thin skin"},
    ]
  },
  "pu1u5": {
    "title": "Happy birthday",
    "words": [
      {"word": "robot", "phonetic": "/ˈrəʊbɒt/", "definition": "a machine that can move and do tasks automatically"},
      {"word": "plane", "phonetic": "/pleɪn/", "definition": "a vehicle with wings that flies through the air"},
      {"word": "house", "phonetic": "/haʊs/", "definition": "a building where people live"},
      {"word": "kite", "phonetic": "/kaɪt/", "definition": "a toy that flies in the wind on a string"},
      {"word": "car", "phonetic": "/kɑː/", "definition": "a vehicle with four wheels used for transport"},
      {"word": "doll", "phonetic": "/dɒl/", "definition": "a toy in the shape of a person"},
      {"word": "ball", "phonetic": "/bɔːl/", "definition": "a round object used in games and sports"},
      {"word": "bike", "phonetic": "/baɪk/", "definition": "a vehicle with two wheels that you pedal"},
      {"word": "ship", "phonetic": "/ʃɪp/", "definition": "a large boat that travels on the sea"},
      {"word": "mouse", "phonetic": "/maʊs/", "definition": "a small furry animal with a long tail"},
      {"word": "radio", "phonetic": "/ˈreɪdiəʊ/", "definition": "a device that receives and plays broadcast sound"},
      {"word": "helicopter", "phonetic": "/ˈhɛlɪkɒptə/", "definition": "an aircraft with rotating blades on top"},
      {"word": "keyboard", "phonetic": "/ˈkiːbɔːd/", "definition": "a set of keys used to type on a computer"},
      {"word": "box", "phonetic": "/bɒks/", "definition": "a container with flat sides used for storing things"},
      {"word": "computer", "phonetic": "/kəmˈpjuːtə/", "definition": "an electronic device for processing information"},
      {"word": "balloon", "phonetic": "/bəˈluːn/", "definition": "a small rubber bag filled with air or gas"},
      {"word": "board game", "phonetic": "/ˈbɔːd ɡeɪm/", "definition": "a game played on a flat board with pieces"},
      {"word": "teddy", "phonetic": "/ˈtɛdi/", "definition": "a soft toy in the shape of a bear"},
    ]
  },
  "pu1u6": {
    "title": "A day out",
    "words": [
      {"word": "shop", "phonetic": "/ʃɒp/", "definition": "a place where you can buy things"},
      {"word": "lorry", "phonetic": "/ˈlɒri/", "definition": "a large vehicle used to transport goods"},
      {"word": "park", "phonetic": "/pɑːk/", "definition": "a public area with grass and trees for recreation"},
      {"word": "motorbike", "phonetic": "/ˈməʊtəbaɪk/", "definition": "a two-wheeled vehicle with an engine"},
      {"word": "flower", "phonetic": "/ˈflaʊə/", "definition": "the colourful part of a plant"},
      {"word": "garden", "phonetic": "/ˈɡɑːdn/", "definition": "an area of land where plants and flowers grow"},
      {"word": "bus", "phonetic": "/bʌs/", "definition": "a large vehicle that carries many passengers"},
      {"word": "bus stop", "phonetic": "/ˈbʌs stɒp/", "definition": "a place where buses stop to let passengers on and off"},
      {"word": "train", "phonetic": "/treɪn/", "definition": "a vehicle that travels on rails"},
      {"word": "tree", "phonetic": "/triː/", "definition": "a tall plant with a trunk and branches"},
      {"word": "snake", "phonetic": "/sneɪk/", "definition": "a long reptile with no legs"},
      {"word": "monkey", "phonetic": "/ˈmʌŋki/", "definition": "a small animal with a long tail that climbs trees"},
      {"word": "hippo", "phonetic": "/ˈhɪpəʊ/", "definition": "a large heavy animal that lives near water"},
      {"word": "lizard", "phonetic": "/ˈlɪzəd/", "definition": "a small reptile with four legs and a long tail"},
      {"word": "giraffe", "phonetic": "/dʒɪˈrɑːf/", "definition": "a very tall African animal with a long neck"},
      {"word": "elephant", "phonetic": "/ˈɛlɪfənt/", "definition": "the largest land animal with a long trunk"},
      {"word": "bear", "phonetic": "/bɛː/", "definition": "a large heavy wild animal with thick fur"},
      {"word": "crocodile", "phonetic": "/ˈkrɒkədaɪl/", "definition": "a large reptile with sharp teeth that lives in rivers"},
      {"word": "polar bear", "phonetic": "/ˈpəʊlə bɛː/", "definition": "a large white bear that lives in the Arctic"},
      {"word": "tiger", "phonetic": "/ˈtaɪɡə/", "definition": "a large wild cat with orange and black stripes"},
      {"word": "zebra", "phonetic": "/ˈzɛbrə/", "definition": "a black and white striped African animal"},
    ]
  },
  "pu1u7": {
    "title": "Let's play",
    "words": [
      {"word": "watch TV", "phonetic": "/wɒtʃ ˌtiːˈviː/", "definition": "to look at and listen to a television programme"},
      {"word": "play basketball", "phonetic": "/pleɪ ˈbɑːskɪtbɔːl/", "definition": "to play a sport where you throw a ball into a hoop"},
      {"word": "play football", "phonetic": "/pleɪ ˈfʊtbɔːl/", "definition": "to play a sport where you kick a ball into a goal"},
      {"word": "play tennis", "phonetic": "/pleɪ ˈtɛnɪs/", "definition": "to play a sport where you hit a ball over a net"},
      {"word": "play the guitar", "phonetic": "/pleɪ ðə ɡɪˈtɑː/", "definition": "to make music using a guitar"},
      {"word": "play the piano", "phonetic": "/pleɪ ðə piˈænəʊ/", "definition": "to make music using a piano"},
      {"word": "ride a bike", "phonetic": "/raɪd ə baɪk/", "definition": "to travel on a bicycle"},
      {"word": "sport", "phonetic": "/spɔːt/", "definition": "a physical activity done for exercise or competition"},
      {"word": "swim", "phonetic": "/swɪm/", "definition": "to move through water using your arms and legs"},
      {"word": "badminton", "phonetic": "/ˈbædmɪntən/", "definition": "a sport played with rackets and a shuttlecock"},
      {"word": "baseball", "phonetic": "/ˈbeɪsbɔːl/", "definition": "a sport played with a bat and ball"},
      {"word": "catching", "phonetic": "/ˈkætʃɪŋ/", "definition": "the action of grabbing something moving through the air"},
      {"word": "hitting", "phonetic": "/ˈhɪtɪŋ/", "definition": "the action of striking something with force"},
      {"word": "kicking", "phonetic": "/ˈkɪkɪŋ/", "definition": "the action of striking something with your foot"},
      {"word": "hockey", "phonetic": "/ˈhɒki/", "definition": "a sport played with sticks and a ball or puck"},
      {"word": "running", "phonetic": "/ˈrʌnɪŋ/", "definition": "moving quickly on foot"},
      {"word": "skateboarding", "phonetic": "/ˈskeɪtbɔːdɪŋ/", "definition": "riding on a flat board with wheels"},
      {"word": "throwing", "phonetic": "/ˈθrəʊɪŋ/", "definition": "the action of sending something through the air"},
    ]
  },
  "pu1u8": {
    "title": "At home",
    "words": [
      {"word": "mirror", "phonetic": "/ˈmɪrə/", "definition": "a glass surface that reflects your image"},
      {"word": "dining room", "phonetic": "/ˈdaɪnɪŋ ruːm/", "definition": "a room where meals are eaten"},
      {"word": "kitchen", "phonetic": "/ˈkɪtʃɪn/", "definition": "a room where food is prepared and cooked"},
      {"word": "living room", "phonetic": "/ˈlɪvɪŋ ruːm/", "definition": "a room in a house used for relaxing"},
      {"word": "bed", "phonetic": "/bɛd/", "definition": "a piece of furniture used for sleeping"},
      {"word": "bedroom", "phonetic": "/ˈbɛdruːm/", "definition": "a room used for sleeping"},
      {"word": "bath", "phonetic": "/bɑːθ/", "definition": "a large container filled with water for washing"},
      {"word": "bathroom", "phonetic": "/ˈbɑːθruːm/", "definition": "a room with a bath or shower and toilet"},
      {"word": "radio", "phonetic": "/ˈreɪdiəʊ/", "definition": "a device that receives and plays broadcast sound"},
      {"word": "armchair", "phonetic": "/ˈɑːmtʃɛː/", "definition": "a comfortable chair with supports for your arms"},
      {"word": "rug", "phonetic": "/rʌɡ/", "definition": "a small carpet placed on the floor"},
      {"word": "sofa", "phonetic": "/ˈsəʊfə/", "definition": "a long comfortable seat for more than one person"},
      {"word": "phone", "phonetic": "/fəʊn/", "definition": "a device used to make and receive calls"},
      {"word": "hall", "phonetic": "/hɔːl/", "definition": "the entrance area inside the front door of a house"},
      {"word": "lamp", "phonetic": "/læmp/", "definition": "a device that produces light"},
      {"word": "clock", "phonetic": "/klɒk/", "definition": "a device that shows the time"},
      {"word": "floor", "phonetic": "/flɔː/", "definition": "the flat surface you walk on inside a building"},
      {"word": "painting", "phonetic": "/ˈpeɪntɪŋ/", "definition": "a picture made with paint, hung on a wall"},
    ]
  },
  "pu1u9": {
    "title": "Happy holidays",
    "words": [
      {"word": "shorts", "phonetic": "/ʃɔːts/", "definition": "short trousers that end above the knee"},
      {"word": "shirt", "phonetic": "/ʃɜːt/", "definition": "a piece of clothing worn on the upper body"},
      {"word": "jeans", "phonetic": "/dʒiːnz/", "definition": "trousers made from denim fabric"},
      {"word": "shoes", "phonetic": "/ʃuːz/", "definition": "coverings worn on the feet"},
      {"word": "hat", "phonetic": "/hæt/", "definition": "a covering worn on the head"},
      {"word": "jacket", "phonetic": "/ˈdʒækɪt/", "definition": "a short coat worn on the upper body"},
      {"word": "dress", "phonetic": "/drɛs/", "definition": "a piece of clothing for women or girls"},
      {"word": "sunglasses", "phonetic": "/ˈsʌnɡlɑːsɪz/", "definition": "glasses with dark lenses to protect eyes from the sun"},
      {"word": "boots", "phonetic": "/buːts/", "definition": "strong shoes that cover the ankle or leg"},
      {"word": "baseball cap", "phonetic": "/ˈbeɪsbɔːl kæp/", "definition": "a cap with a curved brim at the front"},
      {"word": "trousers", "phonetic": "/ˈtraʊzəz/", "definition": "a piece of clothing covering both legs"},
      {"word": "T-shirt", "phonetic": "/ˈtiːʃɜːt/", "definition": "a simple shirt with short sleeves and no collar"},
      {"word": "sun", "phonetic": "/sʌn/", "definition": "the star that gives light and heat to the Earth"},
      {"word": "sand", "phonetic": "/sænd/", "definition": "tiny grains of rock found on beaches and deserts"},
      {"word": "sea", "phonetic": "/siː/", "definition": "a large body of salt water"},
      {"word": "fishing", "phonetic": "/ˈfɪʃɪŋ/", "definition": "the activity of catching fish"},
      {"word": "jellyfish", "phonetic": "/ˈdʒɛlifɪʃ/", "definition": "a sea creature with a soft body and long tentacles"},
      {"word": "camera", "phonetic": "/ˈkæmərə/", "definition": "a device used to take photographs"},
      {"word": "fish", "phonetic": "/fɪʃ/", "definition": "an animal that lives in water and has fins"},
      {"word": "beach", "phonetic": "/biːtʃ/", "definition": "an area of sand or pebbles next to the sea"},
      {"word": "boat", "phonetic": "/bəʊt/", "definition": "a small vehicle used to travel on water"},
      {"word": "shell", "phonetic": "/ʃɛl/", "definition": "the hard outer covering of a sea creature"},
    ]
  },
}

if __name__ == "__main__":
    total = sum(len(v["words"]) for v in PU1_VOCAB.values())
    print(f"Total units: {len(PU1_VOCAB)}")
    print(f"Total words: {total}")
    for k, v in PU1_VOCAB.items():
        print(f"  {k}: {v['title']} - {len(v['words'])} words")
